# Generated by Django 4.1.4 on 2022-12-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='featured_image',
        ),
    ]
