# Generated by Django 4.1.4 on 2022-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fruits',
        ),
        migrations.AddField(
            model_name='cart',
            name='fruits',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
