# Generated by Django 4.1.4 on 2022-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_cart_fruits_cart_fruits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fruits',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
