# Generated by Django 4.1.4 on 2022-12-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_cart_owner_remove_product_fruits_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fruits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
