# Generated by Django 4.1.4 on 2022-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_cart_fruits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_intro',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
