# Generated by Django 4.1.4 on 2022-12-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_selected',
        ),
    ]
