# Generated by Django 4.1.4 on 2022-12-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email'),
        ('products', '0021_remove_product_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
